# Generated by Django 5.0.1 on 2024-01-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidadingerediente',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='delete_at',
        ),
    ]
