# Generated by Django 5.0.1 on 2024-01-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadingerediente',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas.ingrediente'),
        ),
    ]
