# Generated by Django 5.0.1 on 2024-01-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnarok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadingerediente',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ragnarok.ingrediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, to='ragnarok.cantidadingerediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/recetas'),
        ),
    ]
