# Generated by Django 5.0.1 on 2024-01-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragnarok', '0003_alter_receta_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidadingerediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='CantidadIngerediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
